### ISSUE TITLE
Fill up the "License" Wiki page

### ISSUE THREAD

**Issue by SergioLuis** [SergioLuis/CHIPEIT#18]
**Developer**: @ugedo 
**Reviewer**: @mikelcaz 

------

Fill the [License](https://github.com/SergioLuis/CHIPEIT/wiki/License) Wiki page. The work is not started. This should be really easy, remember that we use the GPLv3 license. Look for a template and fill it as necessary.

**Comment by ugedo** [comment]
I Fill the [License](https://github.com/SergioLuis/CHIPEIT/wiki/License) Wiki page with information of GPLv3.
Should we include on this page a text of copyright disclaimer?
Also a copy of the license text must be included somewhere in the distribution. I look forward to determining the location.
Each file should include license notices.. Do I know it on the wiki?

**Comment by SergioLuis** [comment]
Maybe we should add the license header to each source code file... any thoughts @mikelcaz?

**Comment by SergioLuis** [comment]
@mikelcaz Please take a look at this and decide whether we should add the license header to every source code file, or it is just enough to include a copy of the license on the repository (which we already have done).

Thanks!
