### ISSUE TITLE
Fill up the "Credits" Wiki page

### ISSUE THREAD

**Issue by SergioLuis** [SergioLuis/CHIPEIT#19]
**Developer**: @jhvargas3112 
**Reviewer**: @ugedo 

------

Fill the [Credits](https://github.com/SergioLuis/CHIPEIT/wiki/Credits) Wiki page. Find something nice to say about the team, our background, and maybe our links to LinkedIn / Twitter if necessary.

**Comment by jhvargas3112** [comment]
i've wrote an base schema of the wiki's credits section. if you think that i must write any more, please, give me more infromation about you.

**Comment by SergioLuis** [comment]
Reviewed OK.
