### ISSUE TITLE
Fix gradlew permissions

### ISSUE THREAD

**Issue by mikelcaz** [SergioLuis/CHIPEIT#21]
**Developer**: @mikelcaz 
**Reviewer**: @SergioLuis
**Integrator**: @SergioLuis

---

Gradlew (gradle wrapper) files need the executable bit set on unix, as it should be. We are using (octal) 0755 on the other gradlew ones (chipeitlib/android), being console/gradlew the newcomer.  As it was created on a Windows machine, we forget to verify it.

If we need more new executables, we should test them on unix systems first.

**Comment by SergioLuis** [comment]
PR #22 fixes this.
