### ISSUE TITLE
Implement basic application structure

### ISSUE THREAD

**Issue by SergioLuis** [SergioLuis/CHIPEIT#3]
**Developer**: @SergioLuis
**Reviewer**: @mikelcaz 

Please, look at the code: @jhvargas3112 @ugedo 

------

Implement a first draft of the application so the development and testing of the application on Android devices can start.

This task is not to implement the final UI, but to implement a rudimentary version of it that can help us to launch the backend on Android, so the following functionalities are _nice to have_ on this first UI:

* Be able of choosing a ROM to load to the backend.
* Start and stop ROM emulation.
* Display backend errors, if any.

**Comment by SergioLuis** [comment]
This depends on [_Implement general application structure_](https://github.com/SergioLuis/CHIPEIT/issues/1).

**Comment by jhvargas3112** [comment]
Finally, this is the basic prototype for the game running and keyboard layout. There is a doubt to considerate for the screenshot functionality:

Screenshot functionality take an image only of the game section and this aumotically is saved in the sistem. After, user can share this whereever he wants.

![20180321_194135](https://user-images.githubusercontent.com/4223397/37730401-ed4e91c2-2d3f-11e8-8ef3-800f7a1ba37a.jpg)

**Comment by SergioLuis** [comment]
Implemented the following:

- A splash screen
- A game library, with those built-in games we will distribute CHIPEIT with.
- A series of actions for each game, which can be customized if needed.
- A basic emulator activity with the basics: the keyboard and the (not-yet-implemented) emulator screen.

![screenshot_20180515-192451](https://user-images.githubusercontent.com/6057745/40073131-4c0057da-5876-11e8-9eee-058fa0f0d3cb.png)
![screenshot_20180515-192459](https://user-images.githubusercontent.com/6057745/40073137-4f173740-5876-11e8-8f41-0d090366c0f7.png)
![screenshot_20180515-192513](https://user-images.githubusercontent.com/6057745/40073139-50f131e2-5876-11e8-9044-d17437500bfc.png)
![screenshot_20180515-192521](https://user-images.githubusercontent.com/6057745/40073143-5222dc3c-5876-11e8-9aaf-02dda50cd0e7.png)
