### ISSUE TITLE
Design Android UI

### ISSUE THREAD

**Issue by SergioLuis** [SergioLuis/CHIPEIT#4]
**Developers**: @ugedo @jhvargas3112 
**Reviewers**: @mikelcaz @SergioLuis

-------

Design the Android User Interface.

This means: design it, do NOT code it. The functionality the UI must cover is:

* Load a game from the system's file manager.
    * Take a look at how you can upload files using Google Drive.
* ~Quick load a recent game.~ Load a saved game.
* Play the game
    * CHIP-8 uses 16 keys, from 0 to 9 and from A to F.
    * CHIP-8 uses a 64x32 monochrome screen. Be sure to maintain the aspect ratio in the game.
* Quick save a game.
* Screenshot the game's screen and share it (using the Android API. If you need examples, take a look at how you can share a tweet on its official Android application).

You can upload the mockups to a top-level directory in the repository. We'll use this issue to discuss them.

**Comment by SergioLuis** [comment]
@jhvargas3112 @ugedo You can start with this task right now.

**Comment by jhvargas3112** [comment]
Aparte de distinguir las funcionalidades básica del emulador y las partes nice to have, en este momento tengo dilema respecto a la gestión de las roms, la cual considero como funcionalidad básica. Propongo que en el arranque del emulador se busquen todas las roms disponibles en el sistema y se muestren en un listado en la interfaz de usuario, de modo que el usuario pueda efectuar las típicas operaciones sobre ellas (borrar, mover, empezarzar a jugar...).

**Comment by jhvargas3112** [comment]
Por otro lado Mikel propone crear 2 proptotipos de interfaz, una para pantallas grandes y otra para pantallas compactas. De este modo en pantallas grandes usaríamos un tablero para mostrar las roms y en pantallas compactas usaríamos listados.

**Comment by SergioLuis** [comment]
Some minor points:
* First: we agreed on using english as the primary language for the repository. We can discuss that point once again, but until then, please, use english. I think the effort (which I'm doing, too) will be rewarded sooner or later, one way or another.
* Second: if Mikel has any suggestions, he can use this thread himself, as it's purpose is to have a public forum to shape up the user interface.
* Third: we are discussing over thin air, as I don't see any mockups.

Having said that, this is my advice about the part of the interface you are facing trouble with: don't try to reinvent the wheel. Plenty of emulators have already dealt with these issues. I suggest both of you to take a look at their solutions. Install them on your phone and play with them for a while. Find the points where they excell and think about where they do fall short.

* [My Boy! - GBA Emulator](https://play.google.com/store/apps/details?id=com.fastemulator.gba)
* [Visual Boy Advance GBA Emulator Free](https://play.google.com/store/apps/details?id=vba.gba.emulator.gameboyadvance.visualboyadvance.free)
* [John GBA Lite - GBA emulator](https://play.google.com/store/apps/details?id=com.johnemulators.johngbalite)
* [GBA+ Pro Emulator (easyROM)](https://play.google.com/store/apps/details?id=com.easyrom.gbago.gameboyemulator.proprolite)
* [PPSSPP - PSP emulator](https://play.google.com/store/apps/details?id=org.ppsspp.ppsspp)

I'm particularly interested in how the __John GBA Lite__ emulator handles the user library. Each game has a related screenshot. I think that each screenshot was taken while the user was interacting with the game. This way, we could almost guarantee that the screen has a relevant image at the moment of taking the screenshot. Bonus point: this solution would work great with different sized screens. We can make the game's thumbnail as large as necessary, and we can have a flexible number of rows and columns on the grid.

I also really like how the _My Boy! - GBA emulator__ application handles quick loading. Each saving file also has a screenshot, alongside a name, and the exact date it was created at. This way, the user can quickly identify the save state they're interested in, and, just like in the previous example, this can be easily adapted to a wide variety of screen sizes and aspect ratios.

**Comment by jhvargas3112** [comment]
Wes, i like that each game has a related screenshot. My idea of the roms list is inspired by the [**SuperRetro16 game emulator**](https://play.google.com/store/apps/details?id=com.bubblezapgames.supergnes_lite&hl=es_419). Well, we can aggregate the game screenshots both for the roms list and for the saved games. Obviously each saved game should have a date and an hour.

**Comment by mikelcaz** [comment]
May you clarify what is "quick load" and "a recent game"? Thanks.

**Comment by SergioLuis** [comment]
@mikelcaz done. Changed _quick load_ for _load a saved game_. I talked about Google Drive to point out that Android already has a standard user interface to select files from the file system. We are not implementing a "file manager", so I'd like to clarify some points:

* The application does NOT look for ROMs in the system. The user does.
    * We can think about doing this later on, but I don't want to traverse the entire FS in order to find two or three ROMs at most.
    * Implementing this can get tricky really soon. We could only rely on the file extension to identify ROMs, and we could hit some walls, as runtime permissions (starting on Android 6.0), while traversing the FS.
* The ROMs can be arranged in a grid. Each ROM is represented by a screenshot with a title, as proposed before.
    * The grid is responsive by design, and there are grids in the Android's UI framework that provide a lot of functionality to handle the ROMs, like rearranging items or deleting them.
        * Allowing to rearrange ROMs can save us from implementing things such as "favorites". The user could put the ones they play or like the most at the beginning of the grid.
    * In the future we could provide both a grid or a list, depending on the user preferences.
* The first ROM in the grid should be the first one the user added.

So, we would have a grid with _games_ and a grid with _saved games_. Name proposal: _**Game library**_ and _**Saved games**_.

**Comment by mikelcaz** [comment]
Adding:

- Usually, players gets confused between _save_ and _load_ UI, being too similar. I think they suffer something similar between the _game library_ and _saved games_ UI. Both sources of misunderstandings should be avoided regardless the final form of the UI.
- Beware color coding. Users may be color blind.
- What is prioritary, loading a saved game or starting a new game? If it is left to users habits (instead taking our choice), the last used should be prioritary.
- Please don't use dark colors if there is not part of some thematic feeling (like an arcade machine skin ir something like that).

**Comment by SergioLuis** [comment]
@mikelcaz Do you want to actively work on this task along with @jhvargas3112 and @ugedo?

For the color scheme I had something ATARI-like in mind: brown, black, grey, red... and a rainbow ribbon somewhere.

**Comment by mikelcaz** [comment]
PD: I should clarify a little bit what I am thinking with the "what is prioritary" part.

The kind of games you may write in Chip-8 usually are of one single genre. Hardcore games. Of those some users may prefer playing without saving a single time, or start all over.

So continue may not be appropiated as the "always first option".

**Comment by mikelcaz** [comment]
After talking yesterday, I propose the next behavior:

- Every time the player uses the _saved games_ UI or saves a game (explicitly or quitting the application), that UI is set as prioritary.
- Every time the player uses (or returns to) the _game library_ UI, it's set as prioritary.

If the player saved a game (launched from the _game library UI_) and quited the game (but no the application), the _game library_ UI should be shown first for predictability. Making the player change to the _saved games_ won't be as cumbersome as the opposite scenario, too.

But if players quit the whole application (they are in a hurry or want to stop), the _saved games_ UI offers them the chance to continue where they left off.

The good part is: in case a player wants to stop but returns to the menu instead, the situation is a blip. One user indication **just the first time**, and everything goes back to normal the next times.

--- 

**But.**

We should specify what is the sorting of the _saved games_ UI, which I suppose will end being a grid too (there is a correspondence with the sorting of the _game library_ UI?). So my proposal is secondary to this, and should be considered after deciding this, no sooner.

**Comment by mikelcaz** [comment]
About that last point:

Saved games. How many games of a single "title" can be saved? Just one, or several ones? Cause if you have 3 titles in your library (A, B, C), the grid could be like: [A, B, C] and the _saved games_ UI could be like [] (empty).

Then you start playing. You like A and C, but not B. With the time, the _saved games_ could be like [A1, A2, A3, A4, C1, C2, C3]. A little bit chaotic, if you ask.

We should consider this stuff carefully, and be sure that cannot lead to confusion (_saved games_ UI is not _photo gallery_ UI, and saving vs. loading should be clearly distinguished without "color coding" them or relaying on a text label).

**Comment by jhvargas3112** [comment]
@mikelcaz the case you shown is true and it's probably that generate a litle bit confusion. So, i propropose 2 alternatives:

1. Saved games are sorted by title game and date of saving.

2. Saved games administration could be handle on two grids: the first contains a grid of titles and the second grid contains the saved games for each title, sorted by date.

**Comment by SergioLuis** [comment]
Here are my thoughts about the grid sorting politics and displayed data:

* For games:
    * The first one being added is the first one in the grid. This is, the top-left corner.
        * The games are displayed in the library in the same order the user added them.
        * In the future, we could add sorting options: by _played times_, by _date added_, _alphabetically_... whichever we think makes sense. We could even give the possibility to show the games on a list instead of on a grid.
    * For games, we should keep and show the following information:
        * A screenshot (as mentioned before, we have to discuss a heuristic on when to take that screenshot).
        * The name of the game. At first, it will be the name of the file, without the extension, but it would be nice to let the user modify it in the future. It is a _nice to have_ functionality, but I'd like the UI mockups to reflect it.

* For saved games:
    * The first one is the newest one. This is, the last game the user saved.
        * I think that users would usually like to continue their most recent game.
    * For saved games, we should keep and show the following information:
        * A screenshot of the game at the moment the user saved the game.
        * The date when the game was saved.
        * A title, that the user can edit while saving (for example, _My highest score to date_, or _perfect game so far_). Default's title should be something like `[game title]@[date]`.

BUT, I think we are getting ahead of ourselves. This is an iterative process, and we don't have any mockups yet to comment on and change.

**Comment by mikelcaz** [comment]
Your statements are mostly describing the previous proposal, but not addressing the problem.

@jhvargas3112 Sorting by title name (first) won't fix anything, but will be inconsistent with the _game library_ UI.

Example: game_library = [C, A, B], saved_games = [A3, A2, A1, C2, C1].

> C was added first, then A, then B, and 3 is newer than 2, etc.

The second alternative makes me wonder why the _game library_ UI is separated in first place (and I think it should be, at least right now, as I may change my mind on this aspect).

@SergioLuis I understand that you rewrote the _game library_ part for avoid misunderstandings. I mostly agree with that part (except about removing the extension). I would add: top left corner as first element shouldn't be assumed (even if as example made the trick).

The _saved games_ part. Displaying by date (first) regardless to what game belongs that save game is not a good idea IMHO. And it doesn't fix the problem anyway.

Example: game_library = [A, B, C], saved_games = [C2, A3, A2, C1, A1].

In a proper solution is desirable that:

- The player can continue with the last game as soon as possible (a save game can be updated, changing its date).
- The player has not to go though saved games of other titles searching a particular save game of the title he really wants (consider the previous saved_games array, with saved games of 100 titles, searching A1 at the end).

**Comment by SergioLuis** [comment]
@mikelcaz about this:

> _a save game can be updated, changing its date_

I don't think it should. A snapshot is a snapshot, and cannot vary. If the user continues from that snapshot, they can create a new one, but the old one is not modified. I would be angry if my _perfect game_ is overriden, and because handling more options (_save game_ / _update saved game_) would add complexity, I suggest to keep saved games as simple as possible.

And about this:

> _The player has not to go though saved games of other titles searching a particular save game of the title he really wants_

We could add the option to search both games and saved games. But still, I think the odds are that a user would want to continue the last game they saved, and following the criteria I described, it would be the first one in the grid.

**Comment by mikelcaz** [comment]
@SergioLuis I disagree with the first part. But don't mind for now, we will discuse about that later.

The second and prioritary part. I consider that a patch, and as you state, the criteria satisfy the first desirable feature, but not the second one.

I consider using the @jhvargas3112 proposal with a little change, and using two grids without tabs. The first one is the _game library_ UI, and selecting one game, a second with _saved games_ should appear. That UI includes a "new game" button, so the user wouldn't be much overwhelmed.

Of course, that not satisfy the second criteria, but I believe it is a promising starting point and will be easier reach a solution that meets both at once.

**Comment by mikelcaz** [comment]
About the _saved game_ grid: we should reflect somewhere the selected game.

One of the elements of the grid could be the "new game" button.

**Comment by jhvargas3112** [comment]
here is the UI prototype for the "Librería de juegos" section. Any suggestions will be welcome.

![20180315_012306](https://user-images.githubusercontent.com/4223397/37438459-d62fa5c8-27f2-11e8-9a1d-0b5beef0c1f9.jpg)

**Comment by jhvargas3112** [comment]
here is the UI prototype for the "Librería de juegos" section. Any suggestions will be welcome.

![20180315_012306](https://user-images.githubusercontent.com/4223397/37438572-b880bcd2-27f3-11e8-93bf-cdf7f7038554.jpg)

**Comment by mikelcaz** [comment]
@jhvargas3112 We should consider seriously making this stuff in English from the next mock up. All of us have overlooked it ; )

Definitely, _game library_ means 'biblioteca de juegos' (as in "Lugar donde se tiene considerable número de libros para la lectura"). So our _game library_ is a place that collects a considerable number of games waiting to be played.

I'm not sure if this information should be shown (and how) at screen, but here we have a progress making everything be less than two taps or clicks, and removing some clutter in the process (hooray!).

On the other hand, I have no idea about what is the purpose of the _notification zone_. So, what is it?

Plus: I hate that kind of menus with all my soul. Can we consider something like Windows 8 and a lot of Android managers? Using a menu bar with icons, so would be possible selecting and viewing more interactible elements (no overlapping), and take advantage of the Fitts' Law (for touch screen and mouse in one stroke).

It's nice to see we are on the right track.

**Comment by jhvargas3112** [comment]
Here is the English version.

![20180315_132438](https://user-images.githubusercontent.com/4223397/37463506-b2e2f242-2855-11e8-8a8f-d6a88b035ab8.jpg)

**Comment by jhvargas3112** [comment]
This is the prototype for the game running.

![20180320_225538](https://user-images.githubusercontent.com/4223397/37684837-a13d322e-2c91-11e8-8c86-8150bb0d9898.jpg)

**Comment by ugedo** [comment]
Here is the Andrid UI prototype for the "Saved games" section. List and grid versions.
![1-partidas_guardadas](https://user-images.githubusercontent.com/11878229/37729094-57fdb344-2d3c-11e8-9d74-1336d0b94cf1.jpg)

**Comment by jhvargas3112** [comment]
Finally, this is the basic prototype for the game running and keyboard layout. There is a doubt to considerate for the screenshot functionality:

Screenshot functionality take an image only of the game section and this aumotically is saved in the sistem. After, user can share this whereever he wants.

![20180321_194135](https://user-images.githubusercontent.com/4223397/37731325-13a2b3d8-2d42-11e8-8ccf-5516ce16f231.jpg)

**Comment by ugedo** [comment]
Ok @SergioLuis, @mikelcaz, this issue is already waiting for the review to close.

**Comment by SergioLuis** [comment]
About the grid: I'm not a fan of popups. I also find the _Resume_ (_Readunar_) option in the popup troublesome: the user has to long-press a saved game to resume it? It should be the default option, not hidden in a second-level menu.

I like the _Delete_ option, and I did not think about the _Export_ one, nice catch!

Could you redo that screen moving the `Delete` and `Export` options to the toolbar? Hint: check what WhatsApp does when you long-press a message inside a chat.

**Comment by mikelcaz** [comment]
Yes, that's what I meant when I said that about "I hate them with all my soul". That kind of options should be on the toolbar.

Multiple selection would be great, and I insist on adding a checkbox there for selecting/unselecting all the items, like many Android file managers do.

On the _running game_ UI: please, don't put reset there. It's too easy pressing it by mistake. What's more, I'll move that kind of options (reset, snapshot, save) to the matrix keyboard placement while the game is paused.

I propose moving the pause/resume function to the game screen itself (as a video on YouTube). The top screen bar could be deleted (or just use the standard toolbar).

**Comment by SergioLuis** [comment]
I'm closing this issue. Further discussion on the topic will go on the issue of the actual implementation of the UI.
